{{/*
Copyright (c) 2025 VH & Co BV. Licensed under the Business Source License 1.1.
*/}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stackweaver.fullname" . }}-frontend
  labels:
    {{- include "stackweaver.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "stackweaver.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
